// Generated by gencpp from file car_monitor/Goal.msg
// DO NOT EDIT!


#ifndef CAR_MONITOR_MESSAGE_GOAL_H
#define CAR_MONITOR_MESSAGE_GOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace car_monitor
{
template <class ContainerAllocator>
struct Goal_
{
  typedef Goal_<ContainerAllocator> Type;

  Goal_()
    : header()
    , receiver_name()
    , x(0.0)
    , y(0.0)
    , yaw(0.0)
    , if_straight(false)  {
    }
  Goal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , receiver_name(_alloc)
    , x(0.0)
    , y(0.0)
    , yaw(0.0)
    , if_straight(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _receiver_name_type;
  _receiver_name_type receiver_name;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef uint8_t _if_straight_type;
  _if_straight_type if_straight;





  typedef boost::shared_ptr< ::car_monitor::Goal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_monitor::Goal_<ContainerAllocator> const> ConstPtr;

}; // struct Goal_

typedef ::car_monitor::Goal_<std::allocator<void> > Goal;

typedef boost::shared_ptr< ::car_monitor::Goal > GoalPtr;
typedef boost::shared_ptr< ::car_monitor::Goal const> GoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_monitor::Goal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_monitor::Goal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_monitor::Goal_<ContainerAllocator1> & lhs, const ::car_monitor::Goal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.receiver_name == rhs.receiver_name &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw &&
    lhs.if_straight == rhs.if_straight;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_monitor::Goal_<ContainerAllocator1> & lhs, const ::car_monitor::Goal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_monitor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_monitor::Goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_monitor::Goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_monitor::Goal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_monitor::Goal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_monitor::Goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_monitor::Goal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_monitor::Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59f1461cb1d0760166025afddcc1007b";
  }

  static const char* value(const ::car_monitor::Goal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59f1461cb1d07601ULL;
  static const uint64_t static_value2 = 0x66025afddcc1007bULL;
};

template<class ContainerAllocator>
struct DataType< ::car_monitor::Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_monitor/Goal";
  }

  static const char* value(const ::car_monitor::Goal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_monitor::Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"string receiver_name  # 接收车辆名称\n"
"float64 x  # 目标点X坐标\n"
"float64 y  # 目标点Y坐标\n"
"float64 yaw # heading\n"
"bool if_straight #判断接下来是否走直线\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::car_monitor::Goal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_monitor::Goal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.receiver_name);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
      stream.next(m.if_straight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Goal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_monitor::Goal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_monitor::Goal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "receiver_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.receiver_name);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "if_straight: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.if_straight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_MONITOR_MESSAGE_GOAL_H
