global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.5

  update_frequency: 15.0
  publish_frequency: 10.0

  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}


  inflation_layer:
    enabled:              true
    cost_scaling_factor:  3.0  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     1.8  # max. distance from an obstacle at which costs are incurred for planning paths.
    
  # 添加以下参数
  static_layer:
    enabled: true
    lethal_cost_threshold: 45  # 降低致命成本阈值，使机器人更容易探索未知区域

